### PR TITLE
fix(graphql): search @searchable fields inside nested sub-projections

### PR DESCRIPTION
**Pull request by mvhenten**
Closes #158.

`@searchable` on a sub-model's field was recorded in the projection and emitted into the index mapping, then dropped when the free-text field list was built. The field was searchable everywhere except in search. Downstream (stxcommodities/core-services#2679) this silently broke "find by reference" lookups on every projection modelling a child collection as `@nested`.

## Behavior

The resolver collected text fields with a flat pass over the projection's own `fields`, rejecting `nested` and `subProjection` outright. A sub-projection records its own `@searchable` fields in its own `fields` array, so that pass could never see them. The mapping emitter has always recursed; the resolver did not.

The collector now threads paths down the projection tree, the way `buildShapeRecursive` already does on the filter path. How a field is mapped decides where it lands:

- **`object` sub-projection**: same Lucene document, so the field joins the flat `multi_match` under its dotted path (`owner.fullName`).
- **`@nested` sub-projection**: separate hidden documents, unreachable by a bare `multi_match` on `tags.note`. Each `@nested` sub-model carrying searchable text contributes one `nested`-wrapped clause, combined under `bool.should` with `minimum_should_match: 1`. `score_mode: "max"` scores a parent by its best-matching child.

Paths are fully known at emit time, so the clause is a static literal — no runtime spec walk, and none of the APPSYNC_JS control-flow constraints apply.

`@searchable` is the opt-in; no new decorator. It was inert before, so no caller can be relying on today's behavior — but **this widens the `multi_match` of any existing projection with nested `@searchable` fields, which changes relevance scoring downstream even where it is strictly a fix.** Nested matches now rank against root-field matches.

A projection with no nested searchable text emits the flat `multi_match` byte-for-byte, and the helper is not emitted at all. Only `pet-search-doc-fn-prepare.js` moves in the baseline snapshot, and only in that clause.

## Resolver size

The nested clause is the one part of `buildQuery` that scales with sub-model count. Inlining the skeleton per group cost ~157 bytes each; factoring it into an `NQ` helper, as `ADH` already does for histogram entries, cuts that to ~56 plus 166 bytes once and pushes the width at which a projection would hit the 32 KB cap further out. Projections without nested searchable text pay nothing.

| Projection | Before | After |
| --- | --- | --- |
| petstore fixture (`pet-search-doc-fn-prepare.js`, 1 nested group) | 13,728 | 13,994 |
| counterparty shape (7 nested sub-models, 2 text fields each) | — | 24,617 (headroom 8,151) |
| synthetic wide guard (14 sub-models, no nested text) | 32,452 | 32,452 (unchanged) |

The 14-sub-model guard is all `@keyword`/date sub-models, so it pays nothing and stays at its documented 316-byte headroom. A projection that wide *and* with searchable text in every sub-model would exceed the cap: at that width the nested clause adds 984 bytes against 316 bytes of headroom, and the failure surfaces as a deploy-time `BadRequestException`, not a red CI (#101, #105). Real shapes are far from it; the counterparty shape stays monolithic.

## Tests

`src/emit-graphql-resolver.test.ts:293-308` pinned the defect, asserting `["name"]` for a projection containing nested/sub-projection fields. Inverted: its sub-projections now carry real fields and it asserts the wrapped clause. The tests execute the generated `buildQuery` and assert the query object, rather than matching source text.

Covering each acceptance point: the nested wrapper with `minimum_should_match: 1`; object sub-projections resolving via dotted paths; `@analyzer` on a nested field honoured (queries the analyzed path, not `.keyword`); grouping by innermost nested ancestor; `@searchAs` projected names; byte-for-byte flat output when nothing nested is searchable; and a width guard that the nested clause keeps the counterparty shape under the cap.

### CODE REVIEW

**Review by mvhenten — COMMENTED** [review]
Reviewed against #158's Acceptance list, with every reported number re-measured independently in a clean worktree at `a7f2e18`.

**The fix itself is correct.** The collector's path threading matches `buildShapeRecursive`'s (`filters.ts`) — one `fieldPrefix` for the dotted path, a separate `nestedPath` for the innermost nested ancestor, which is the right split for the free-text axis. The emitted clause matches the shape #158 specified exactly, and I confirmed it against the emitted mapping: `pet-search-doc-search-mapping.json` maps `tags` as `{"type":"nested"}` with `tags.note` as `text`, and the resolver emits `NQ("tags", ["tags.note"], queryText)` under `bool.should` with `minimum_should_match: 1`. Recursion is safe — `buildVirtualSubProjection` (`projection.ts:528`) already cycle-guards with a visited-name set, so the resolved tree is acyclic.

Acceptance, verified point by point:

- Nested wrapper with `minimum_should_match: 1` — yes; `path`, `score_mode: "max"`, inner `multi_match` all present.
- `@analyzer` honoured — yes; the collector never appends `.keyword` and excludes `field.keyword`, so an analyzed path is what gets queried.
- `object` sub-projections take the flat dotted path with no wrapper — yes.
- Byte-for-byte flat output — yes. `git diff --stat origin/main -- test/snapshots/` shows exactly one file moves (`pet-search-doc-fn-prepare.js`), and it legitimately has nested searchable text.
- Inverted test — yes, and the suite discriminates: PR tests against `origin/main`'s emitter give **5 failures**, including the inverted one.
- Under the 32 KB cap — yes. Re-measured: counterparty+text `prepare` = **24,617** (headroom 8,151), 14-sub-model guard = **32,452** (headroom 316), identical to main. The guard's sub-models really are all `@keyword`/`utcDateTime`, so the "pays nothing" claim holds.

`NQ` does not violate any APPSYNC_JS constraint — no `while`/`continue`/C-style `for`/`++`/`--`/recursion, no runtime spec walk. This is genuinely covered, not asserted: the eslint fixture's `nestedTagSubProjection()` carries searchable text (`note`), so `NQ` is in the output that `@aws-appsync/eslint-plugin` lints.

---

### 1. Semantic conflict with #159 — merged result does not compile

This is the one thing that needs action before merge, and neither PR's CI will catch it.

#159 replaces the `ResolvedProjection` import in `src/emit-graphql-resolver.ts` with `TopLevelProjection`. This PR adds two functions that reference `ResolvedProjection`:

- `src/emit-graphql-resolver.ts:260` — `collectTextFields(projection: ResolvedProjection)`
- `src/emit-graphql-resolver.ts:268` — `collectTextFieldsRecursive(projection: ResolvedProjection, …)`

Git merges the two **cleanly** — no textual conflict, nothing to resolve by hand. The merged tree then fails `tsc`:

```
src/emit-graphql-resolver.ts(260,14): error TS2552: Cannot find name 'ResolvedProjection'.
src/emit-graphql-resolver.ts(268,14): error TS2552: Cannot find name 'ResolvedProjection'.
```

Verified by merging `#159`'s head into this branch and running `npx tsc --noEmit`. `npm run test:unit` still passes (tsx does not typecheck), so only `npm run build` surfaces it.

Whichever of #159/#161 lands second must rebase and re-add `ResolvedProjection` to the import list. Without a rebase, **main goes red on the second merge**. Suggested order: **#159 first** (it is the breaking-change PR and its diff here is two type annotations), then rebase this one — the fix is a one-line import.

### 2. `13,929` in the PR body is wrong — the real number is `13,994`

The issue explicitly asks for before/after bytes, so the reported figure matters.

```
main:  test/snapshots/opensearch-baseline/pet-search-doc-fn-prepare.js = 13,728
PR:    test/snapshots/opensearch-baseline/pet-search-doc-fn-prepare.js = 13,994
```

The committed snapshot is byte-identical to a fresh `npm run test:emit`, so 13,994 is what the emitter actually produces. The delta is **+266**, not +201. Branch is a single commit, so this was never a stale measurement of an earlier state. Please correct the table. Every other number in the body and the README table checks out exactly.

### 3. The helper is the right call, but not for the stated reason

The per-group measurement is accurate — I measured inline at **~157 bytes/group** and the helper at **~56 bytes/group + 166 once**, against the body's "~153" and "~53 + 166". Good.

But the framing that inlining "breaches the cap at width" does not justify the helper, because **the helper breaches at the same width**. Taking the 14-sub-model guard fixture and giving every sub-model two searchable text fields:

| variant | `prepare` bytes | headroom |
| --- | --- | --- |
| inline | 34,684 | **−1,916** |
| `NQ` helper | 33,436 | **−668** |

Both are over. The helper's actual merit is what the PR body already says on its own terms — ~100 bytes/group saved, consistent with the `ADH` precedent, and it pushes the breach width outward. That stands without the breach argument; I'd drop the breach framing rather than lean on it.

Minor: `ADH` is emitted as an arrow const (`const ADH = (f, m) => ({…})`, `:1185`) while `NQ` is a function declaration. Same pattern, cosmetically divergent; an arrow const would also be a few bytes shorter. Not worth a round trip on its own.

### 4. The documented gap is honest, with one caveat

Documenting rather than widening the guard fixture is defensible. The shape that breaches (14 sub-models *and* searchable text in every one) is far from anything real — the counterparty shape that reported the bug sits at 8,151 bytes of headroom — and the feature is charged only to projections that use it. The new counterparty+text guard is the guard that matters for this feature, and it is well under.

The caveat: "as the 316-byte headroom already implies for any addition" understates it slightly. The nested clause is not a constant addition at that width — it is 984 bytes, ~3x the remaining headroom. Worth saying plainly, since #101 and #105 both breached in production and the failure mode here is a deploy-time `BadRequestException` rather than a red CI. Not a defect, and not a reason to hold the PR.

### 5. Scoring change

Stated plainly and in bold in the PR body, and again in the README section. Not buried. No complaint.

### Copilot

No Copilot review or comments on this PR (`/reviews` and `/comments` both empty; no reviewer requested). Nothing to triage — flagging so it is not mistaken for a clean pass from a reviewer that never ran.

---

**Verdict: approve on the code; do not merge before resolving (1).** The implementation meets every acceptance point and the suite discriminates against pre-fix code. Rebase after #159 and fix the import, and correct the 13,994 figure in the body.

**Comment by mvhenten** [comment]
Review addressed at 8ddb5ba:

- (1) Rebased onto main past #159; `ResolvedProjection` re-added to the import list. `tsc --noEmit` and the full `npm test` chain (405 unit + 27 example tests) pass on the merged result.
- (2) Body table corrected to 13,994 (+266), re-measured against a fresh `npm run build` in this worktree.
- (3) Breach framing dropped; the helper stands on bytes saved, the `ADH` precedent, and pushing the breach width outward. Per-group figures updated to the re-measured ~157/~56.
- (4) The wide-guard caveat now states the 984-byte clause against 316 bytes of headroom and the deploy-time `BadRequestException` failure mode plainly.
